ROLE_SUPERADMIN = "superadmin"
ROLE_ADMIN = "admin"
ROLE_IT_LEAD = "it_lead"
ROLE_IT_AGENT = "it_agent"
ROLE_RECRUITER = "recruiter"
ROLE_MANAGER = "manager"
ROLE_EMPLOYEE = "employee"

ROLE_VALUES = [
    ROLE_SUPERADMIN,
    ROLE_ADMIN,
    ROLE_IT_LEAD,
    ROLE_IT_AGENT,
    ROLE_RECRUITER,
    ROLE_MANAGER,
    ROLE_EMPLOYEE,
]

STATUS_ACTIVE = "ACTIVE"
STATUS_INACTIVE = "INACTIVE"

USER_STATUS_VALUES = [STATUS_ACTIVE, STATUS_INACTIVE]

IT_STATUS_OPEN = "OPEN"
IT_STATUS_TRIAGED = "TRIAGED"
IT_STATUS_IN_PROGRESS = "IN_PROGRESS"
IT_STATUS_WAITING_ON_USER = "WAITING_ON_USER"
IT_STATUS_RESOLVED = "RESOLVED"
IT_STATUS_CLOSED = "CLOSED"
IT_STATUS_REOPENED = "REOPENED"

IT_STATUS_VALUES = [
    IT_STATUS_OPEN,
    IT_STATUS_TRIAGED,
    IT_STATUS_IN_PROGRESS,
    IT_STATUS_WAITING_ON_USER,
    IT_STATUS_RESOLVED,
    IT_STATUS_CLOSED,
    IT_STATUS_REOPENED,
]

IT_PRIORITY_P0 = "P0"
IT_PRIORITY_P1 = "P1"
IT_PRIORITY_P2 = "P2"
IT_PRIORITY_P3 = "P3"

IT_PRIORITY_VALUES = [IT_PRIORITY_P0, IT_PRIORITY_P1, IT_PRIORITY_P2, IT_PRIORITY_P3]

IT_IMPACT_HIGH = "HIGH"
IT_IMPACT_MEDIUM = "MEDIUM"
IT_IMPACT_LOW = "LOW"

IT_URGENCY_HIGH = "HIGH"
IT_URGENCY_MEDIUM = "MEDIUM"
IT_URGENCY_LOW = "LOW"

IT_IMPACT_VALUES = [IT_IMPACT_HIGH, IT_IMPACT_MEDIUM, IT_IMPACT_LOW]
IT_URGENCY_VALUES = [IT_URGENCY_HIGH, IT_URGENCY_MEDIUM, IT_URGENCY_LOW]

IT_ATTACHMENT_STORAGE_VALUES = ["drive", "local", "url"]

# IT Assets
IT_ASSET_STATUS_IN_STOCK = "IN_STOCK"
IT_ASSET_STATUS_ASSIGNED = "ASSIGNED"
IT_ASSET_STATUS_RETIRED = "RETIRED"
IT_ASSET_STATUS_LOST = "LOST"

IT_ASSET_STATUS_VALUES = [
    IT_ASSET_STATUS_IN_STOCK,
    IT_ASSET_STATUS_ASSIGNED,
    IT_ASSET_STATUS_RETIRED,
    IT_ASSET_STATUS_LOST,
]

IT_ASSET_TYPE_LAPTOP = "LAPTOP"
IT_ASSET_TYPE_DESKTOP = "DESKTOP"
IT_ASSET_TYPE_MONITOR = "MONITOR"
IT_ASSET_TYPE_PHONE = "PHONE"
IT_ASSET_TYPE_TABLET = "TABLET"
IT_ASSET_TYPE_OTHER = "OTHER"

IT_ASSET_TYPE_VALUES = [
    IT_ASSET_TYPE_LAPTOP,
    IT_ASSET_TYPE_DESKTOP,
    IT_ASSET_TYPE_MONITOR,
    IT_ASSET_TYPE_PHONE,
    IT_ASSET_TYPE_TABLET,
    IT_ASSET_TYPE_OTHER,
]

# IT Licenses
IT_LICENSE_TYPE_SUBSCRIPTION = "SUBSCRIPTION"
IT_LICENSE_TYPE_PERPETUAL = "PERPETUAL"

IT_LICENSE_TYPE_VALUES = [IT_LICENSE_TYPE_SUBSCRIPTION, IT_LICENSE_TYPE_PERPETUAL]

IT_BILLING_CYCLE_MONTHLY = "MONTHLY"
IT_BILLING_CYCLE_ANNUAL = "ANNUAL"
IT_BILLING_CYCLE_QUARTERLY = "QUARTERLY"
IT_BILLING_CYCLE_ONE_TIME = "ONE_TIME"

IT_BILLING_CYCLE_VALUES = [
    IT_BILLING_CYCLE_MONTHLY,
    IT_BILLING_CYCLE_QUARTERLY,
    IT_BILLING_CYCLE_ANNUAL,
    IT_BILLING_CYCLE_ONE_TIME,
]
