-- Candidate assessment form storage (candidate-facing)

CREATE TABLE IF NOT EXISTS rec_candidate_assessment (
  candidate_assessment_id INT NOT NULL AUTO_INCREMENT,
  candidate_id INT NOT NULL,
  assessment_token VARCHAR(64) NULL,
  assessment_sent_at DATETIME NULL,
  assessment_submitted_at DATETIME NULL,

  position_applied_for VARCHAR(150) NULL,
  total_experience_years DECIMAL(4,1) NULL,
  architecture_interior_experience_years DECIMAL(4,1) NULL,
  personal_email VARCHAR(255) NULL,
  contact_number VARCHAR(50) NULL,
  current_employment_status VARCHAR(100) NULL,
  interviewer_name VARCHAR(150) NULL,
  notice_period_or_joining_time VARCHAR(100) NULL,
  current_location VARCHAR(100) NULL,

  current_job_duration_months INT NULL,
  current_job_org_name VARCHAR(255) NULL,
  current_job_role_responsibilities TEXT NULL,
  previous_job_duration_months INT NULL,
  previous_job_org_name VARCHAR(255) NULL,
  previous_job_role_responsibilities TEXT NULL,

  education_10th_specialization VARCHAR(150) NULL,
  education_10th_year VARCHAR(10) NULL,
  education_10th_institution VARCHAR(255) NULL,
  education_10th_marks VARCHAR(50) NULL,
  education_12th_specialization VARCHAR(150) NULL,
  education_12th_year VARCHAR(10) NULL,
  education_12th_institution VARCHAR(255) NULL,
  education_12th_marks VARCHAR(50) NULL,
  education_graduation_specialization VARCHAR(150) NULL,
  education_graduation_year VARCHAR(10) NULL,
  education_graduation_institution VARCHAR(255) NULL,
  education_graduation_marks VARCHAR(50) NULL,
  education_post_graduation_specialization VARCHAR(150) NULL,
  education_post_graduation_year VARCHAR(10) NULL,
  education_post_graduation_institution VARCHAR(255) NULL,
  education_post_graduation_marks VARCHAR(50) NULL,

  training1_name VARCHAR(150) NULL,
  training1_year VARCHAR(10) NULL,
  training1_institute VARCHAR(255) NULL,
  training2_name VARCHAR(150) NULL,
  training2_year VARCHAR(10) NULL,
  training2_institute VARCHAR(255) NULL,

  skill_auto_cad INT NULL,
  skill_sketch_up INT NULL,
  skill_revit INT NULL,
  skill_photoshop INT NULL,
  skill_illustrator INT NULL,
  skill_ms_office INT NULL,
  skill_3d_max INT NULL,
  skill_indesign INT NULL,
  skill_presentation INT NULL,
  skill_rhino INT NULL,
  skill_boqs INT NULL,
  skill_analytical_writing INT NULL,
  skill_graphics INT NULL,
  skill_drafting INT NULL,
  skill_hand_sketching INT NULL,
  skill_estimation INT NULL,
  skill_specifications INT NULL,
  skill_enscape INT NULL,

  proficiency_execution_action_orientation INT NULL,
  proficiency_execution_self_discipline INT NULL,
  proficiency_execution_independent_decision INT NULL,
  proficiency_process_time_management INT NULL,
  proficiency_process_following_processes INT NULL,
  proficiency_process_new_processes INT NULL,
  proficiency_strategic_long_term_thinking INT NULL,
  proficiency_strategic_ideation_creativity INT NULL,
  proficiency_strategic_risk_taking INT NULL,
  proficiency_people_collaboration INT NULL,
  proficiency_people_coaching INT NULL,
  proficiency_people_feedback INT NULL,
  proficiency_people_conflict_resolution INT NULL,

  proficiency_reason_execution TEXT NULL,
  proficiency_reason_process TEXT NULL,
  proficiency_reason_strategic TEXT NULL,
  proficiency_reason_people TEXT NULL,

  self_strengths TEXT NULL,
  self_improvement_areas TEXT NULL,
  self_learning_needs TEXT NULL,

  q1_why_studio_lotus TEXT NULL,
  q2_project_scale TEXT NULL,
  q3_role_site_experience TEXT NULL,
  q4_inspired_project TEXT NULL,
  q5_two_year_plan TEXT NULL,

  reference1_name VARCHAR(150) NULL,
  reference1_contact VARCHAR(50) NULL,
  reference1_relationship VARCHAR(255) NULL,
  reference2_name VARCHAR(150) NULL,
  reference2_contact VARCHAR(50) NULL,
  reference2_relationship VARCHAR(255) NULL,

  declaration_name VARCHAR(150) NULL,
  declaration_signature VARCHAR(150) NULL,
  declaration_date DATE NULL,
  declaration_accepted BOOLEAN NOT NULL DEFAULT 0,

  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (candidate_assessment_id),
  UNIQUE KEY uq_rec_candidate_assessment_candidate (candidate_id),
  UNIQUE KEY uq_rec_candidate_assessment_token (assessment_token),
  CONSTRAINT fk_rec_candidate_assessment_candidate
    FOREIGN KEY (candidate_id) REFERENCES rec_candidate(candidate_id)
    ON DELETE CASCADE
);
