CREATE TABLE IF NOT EXISTS rec_candidate_joining_profile (
  candidate_id INT NOT NULL,
  personal_id VARCHAR(64) NULL,
  middle_name VARCHAR(255) NULL,
  date_of_birth DATE NULL,
  gender VARCHAR(50) NULL,
  marital_status VARCHAR(50) NULL,
  marriage_date DATE NULL,
  blood_group VARCHAR(50) NULL,
  physically_handicapped VARCHAR(50) NULL,
  nationality VARCHAR(100) NULL,
  mobile_number VARCHAR(50) NULL,
  personal_email VARCHAR(255) NULL,
  current_address_line_1 VARCHAR(255) NULL,
  current_address_line_2 VARCHAR(255) NULL,
  current_address_city VARCHAR(100) NULL,
  current_address_state VARCHAR(100) NULL,
  current_address_zip VARCHAR(50) NULL,
  current_address_country VARCHAR(100) NULL,
  permanent_address_line_1 VARCHAR(255) NULL,
  permanent_address_line_2 VARCHAR(255) NULL,
  permanent_address_city VARCHAR(100) NULL,
  permanent_address_state VARCHAR(100) NULL,
  permanent_address_zip VARCHAR(50) NULL,
  permanent_address_country VARCHAR(100) NULL,
  father_name VARCHAR(255) NULL,
  mother_name VARCHAR(255) NULL,
  spouse_name VARCHAR(255) NULL,
  children_names LONGTEXT NULL,
  aadhaar_number VARCHAR(64) NULL,
  pf_number VARCHAR(64) NULL,
  uan_number VARCHAR(64) NULL,
  profile_status VARCHAR(32) NOT NULL DEFAULT 'draft',
  pan_verified TINYINT(1) NOT NULL DEFAULT 0,
  aadhaar_verified TINYINT(1) NOT NULL DEFAULT 0,
  submitted_at DATETIME NULL,
  verified_at DATETIME NULL,
  created_at DATETIME NULL,
  updated_at DATETIME NULL,
  PRIMARY KEY (candidate_id),
  KEY idx_rec_candidate_joining_profile_status (profile_status),
  CONSTRAINT fk_rec_candidate_joining_profile_candidate
    FOREIGN KEY (candidate_id) REFERENCES rec_candidate(candidate_id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
